version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: bgdefender-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bg_defender
      MYSQL_USER: bg_user
      MYSQL_PASSWORD: bg_password
    ports:
      - "3306:3306"
    volumes:  
      - bgdefender_mysql_data:/var/lib/mysql

volumes:
  bgdefender_mysql_data:
